name: Maven release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release'
        required: true
      next_dev_version:
        description: 'Next development version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Merge develop -> master
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: develop
          target_branch: master
          github_token: ${{ github.token }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: be-release
          server-username: DEPLOY_USERNAME
          server-password: DEPLOY_PASSWORD
      - name: Maven release prepare
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email github-actions@github.com
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a ${SSH_AUTH_SOCK} > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          mvn -B release:prepare -DreleaseVersion=${INPUT_RELEASE_VERSION} -DdevelopmentVersion=${INPUT_NEXT_DEV_VERSION}-SNAPSHOT -Dtag=v${INPUT_RELEASE_VERSION}
        env:
          github_token: ${{ github.token }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - name: Maven release perform
        run: mvn -B release:perform -Dmaven.test.skip=true
        env:
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: master
          target_branch: develop
          github_token: ${{ github.token }}
