name: Maven release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to release'
        required: true
      next-dev-version:
        description: 'Next development version'
        required: true
      scm-tag:
        description: 'SCM tag for release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Merge develop -> master
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: develop
          target_branch: master
          github_token: ${{ github.token }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: be-release
          server-username: DEPLOY_USERNAME
          server-password: DEPLOY_PASSWORD
      - name: Maven release prepare
        run: mvn -B release:prepare -DreleaseVersion=${INPUT_RELEASE-VERSION} -DdevelopmentVersion=${INPUT_NEXT-DEV-VERSION} -Dtag=${INPUT_SCM-TAG}
        env:
          github_token: ${{ github.token }}
      - name: Maven release perform
        run: mvn -B release:perform -Dmaven.test.skip=true
        env:
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ github.token }}
