name: Maven release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to release'
        required: true
      next-version:
        description: 'Next development version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Merge develop -> master
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: develop
          target_branch: master
          github_token: ${{ github.token }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: be-release
          server-username: DEPLOY_USERNAME
          server-password: DEPLOY_PASSWORD
      - name: Maven release prepare
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email github-actions@github.com
          git pull
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a ${SSH_AUTH_SOCK} > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          mvn -B release:prepare -DreleaseVersion=${RELEASE_VERSION} -DdevelopmentVersion=${NEXT_DEV_VERSION} -Dtag=${SCM_TAG}
        env:
          github_token: ${{ github.token }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          RELEASE_VERSION: ${{ github.event.inputs.release-version }}
          NEXT_DEV_VERSION: ${{ format('{0}-SNAPSHOT', github.event.inputs.next-version) }}
          SCM_TAG: ${{ format('v{0}', github.event.inputs.release-version) }}
      - name: Maven release perform
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email github-actions@github.com
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          mvn -B release:perform -Dmaven.test.skip=true
        env:
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: master
          target_branch: develop
          github_token: ${{ github.token }}
